version: '3.6'

services:
  db:
    image: supabase/postgres:14.1.0
    container_name: supabase_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres

  api:
    image: supabase/gotrue:latest
    container_name: supabase_gotrue
    ports:
      - "9999:9999"
    depends_on:
      - db
    environment:
      GOTRUE_JWT_SECRET: supersecretjwtkey
      GOTRUE_DB_DATABASE_URL: postgres://postgres:supersecurepassword@db:5432/postgres

  realtime:
    image: supabase/realtime:latest
    container_name: supabase_realtime
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:supersecurepassword@db:5432/postgres

  storage:
    image: supabase/storage-api:latest
    container_name: supabase_storage
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      POSTGREST_URL: http://postgrest:3000
      DATABASE_URL: postgres://postgres:supersecurepassword@db:5432/postgres

  postgrest:
    image: postgrest/postgrest:latest
    container_name: supabase_postgrest
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PGRST_DB_URI: postgres://postgres:supersecurepassword@db:5432/postgres
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: supersecretjwtkey

volumes:
  db_data:
